/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proceso;

/**
 *
 * @author SENA
 */
public class Inicio extends javax.swing.JFrame {
 String datos= "" ;
  int num1 = 0, num2 = 0, suma = 0 ;
  
  
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lmostrar = new javax.swing.JLabel();
        Te = new javax.swing.JTextField();
        Bmostrar = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        Bmas = new javax.swing.JButton();
        Bigual = new javax.swing.JButton();
        Bconcad2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Lmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 40, 210, 30));
        getContentPane().add(Te, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        Bmostrar.setText("evaluar1");
        Bmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(Bmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        Bmas.setText("+");
        Bmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmasActionPerformed(evt);
            }
        });
        getContentPane().add(Bmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        Bigual.setText("=");
        Bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigualActionPerformed(evt);
            }
        });
        getContentPane().add(Bigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        Bconcad2.setText("cancatenar");
        getContentPane().add(Bconcad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmostrarActionPerformed
        Lmostrar.setText(Te.getText());
    }//GEN-LAST:event_BmostrarActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
      datos = datos + "1";
        Lmostrar.setText(datos);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
      datos = datos + "2";
        Lmostrar.setText(datos);
        datos = "";
    }//GEN-LAST:event_B2ActionPerformed

    private void BmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmasActionPerformed
       num1=Integer.parseInt(datos);
        Lmostrar.setText(datos);
    }//GEN-LAST:event_BmasActionPerformed

    private void BigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigualActionPerformed
       num2 = Integer.parseInt(datos);
       suma = num1 + num2;
       Lmostrar.setText("" + suma);
    }//GEN-LAST:event_BigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton Bconcad2;
    private javax.swing.JButton Bigual;
    private javax.swing.JButton Bmas;
    private javax.swing.JButton Bmostrar;
    private javax.swing.JLabel Lmostrar;
    private javax.swing.JTextField Te;
    // End of variables declaration//GEN-END:variables
}
